name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      test_category:
        description: 'E2E test category to run. Select "none" to run only unit tests.'
        required: true
        type: choice
        default: 'none'
        options:
          - none
          - planning_and_problem_solving
          - information_retrieval
          - data_driven_decision_making_and_reasoning
          - sophisticated_memory
          - contextual_understanding_infeasible_tasks
  schedule:
    - cron: '25 18 * * *' # Temporary schedule for testing
    - cron: '59 23 * * 2'
    - cron: '59 23 * * 3'
    - cron: '59 23 * * 4'
    - cron: '59 23 * * 5'

jobs:

  code-format:
    runs-on: ubuntu-22.04  # Changed from ubuntu-latest
    if: github.event_name != 'schedule' && (github.event_name != 'workflow_dispatch' || github.event.inputs.test_category == 'none')
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Pip install
        run: pip install black[jupyter]==24.2.0 blacken-docs

      - name: Pip list
        run: pip list

      - name: Code Formatting
        run: black . --check

  browsergym-workarena-fast:
    runs-on: ubuntu-22.04  # Changed from ubuntu-latest
    if: github.event_name != 'schedule' && (github.event_name != 'workflow_dispatch' || github.event.inputs.test_category == 'none')
  
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
  
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
  
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
  
      - name: Pip list
        run: pip list
  
      - name: Install Playwright
        run: playwright install --with-deps
  
      - name: Run non-slow browsergym-workarena Unit Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
        run: pytest -n 5 --durations=10 -m 'not slow and not pricy' --slowmo 1000 -v tests

  browsergym-workarena-slow:
    runs-on: ubuntu-22.04  # Changed from ubuntu-latest
    if: github.event_name != 'schedule' && (github.event_name != 'workflow_dispatch' || github.event.inputs.test_category == 'none')

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt

      - name: Pip list
        run: pip list

      - name: Install Playwright
        run: playwright install --with-deps

      - name: Run slow browsergym-workarena Unit Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
        run: pytest -n 5 --durations=10 -m 'slow and not pricy' --slowmo 1000 -v tests
  
  end-to-end-tests-planning:
    runs-on: ubuntu-22.04
    if: (github.event_name == 'schedule' && github.event.schedule == '25 18 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_category == 'planning_and_problem_solving')
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run E2E Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
          TEST_CATEGORY: planning_and_problem_solving
        run: pytest -n 5 --durations=10 -m 'pricy' --slowmo 1800 -v tests

  end-to-end-tests-information-retrieval:
    runs-on: ubuntu-22.04
    if: (github.event_name == 'schedule' && github.event.schedule == '59 23 * * 2') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_category == 'information_retrieval')
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run E2E Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
          TEST_CATEGORY: information_retrieval
        run: pytest -n 5 --durations=10 -m 'pricy' --slowmo 1800 -v tests

  end-to-end-tests-data-driven-decision-making:
    runs-on: ubuntu-22.04
    if: (github.event_name == 'schedule' && github.event.schedule == '59 23 * * 3') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_category == 'data_driven_decision_making_and_reasoning')
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run E2E Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
          TEST_CATEGORY: data_driven_decision_making_and_reasoning
        run: pytest -n 5 --durations=10 -m 'pricy' --slowmo 1800 -v tests

  end-to-end-tests-sophisticated-memory:
    runs-on: ubuntu-22.04
    if: (github.event_name == 'schedule' && github.event.schedule == '59 23 * * 4') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_category == 'sophisticated_memory')
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run E2E Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
          TEST_CATEGORY: sophisticated_memory
        run: pytest -n 5 --durations=10 -m 'pricy' --slowmo 1800 -v tests

  end-to-end-tests-contextual-understanding:
    runs-on: ubuntu-22.04
    if: (github.event_name == 'schedule' && github.event.schedule == '59 23 * * 5') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_category == 'contextual_understanding_infeasible_tasks')
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        working-directory: ./dev
        run: pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run E2E Tests
        env:
          SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
          SNOW_INSTANCE_UNAME: ${{ secrets.SNOW_INSTANCE_UNAME }}
          SNOW_INSTANCE_PWD: ${{ secrets.SNOW_INSTANCE_PWD }}
          TEST_CATEGORY: contextual_understanding_infeasible_tasks
        run: pytest -n 5 --durations=10 -m 'pricy' --slowmo 1800 -v tests